sonar.projectKey=camilobr89_eps-frontend
sonar.organization=camilobr89
sonar.host.url=https://sonarcloud.io
sonar.branch.name=main

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.jsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/components/ui/**

sonar.coverage.exclusions=**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.jsx,src/main.jsx,src/setupTests.js,src/App.jsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8